name: flet_open_file
description: Flet FletOpenFile control
repository: https://github.com/creeper19472/flet-open-file/src/flutter/flet_open_file
version: 0.1.0
homepage: https://github.com/creeper19472/flet-open-file

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
